import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './supabase';

export default function CanonicalPublishWorkspace(){
  const [rows,setRows]=useState([]),[selectedId,setSelectedId]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState('09:00'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const selected=useMemo(()=>rows.find(r=>r.id===selectedId)||null,[rows,selectedId]);
  const scheduled=rows.filter(r=>r.scheduled_at).length;
  const ready=rows.filter(r=>/draft|ready|pending/i.test(String(r.status||''))).length;
  async function load(){const {data,error}=await supabase.from('track_b_publications').select('id,title,platform,status,scheduled_at,publish_attempts,last_error,created_at,updated_at,project_id,production_job_id').order('updated_at',{ascending:false}).limit(100);if(error)setMessage(error.message);else setRows(data||[])}
  useEffect(()=>{load();const t=setInterval(load,8000);return()=>clearInterval(t)},[]);
  async function schedule(){if(!selected)return;if(!date){setMessage('Choose a date first.');return}setBusy(true);setMessage('Scheduling…');try{const at=new Date(`${date}T${time||'09:00'}:00`).toISOString();const {error}=await supabase.from('track_b_publications').update({status:'scheduled',scheduled_at:at}).eq('id',selected.id);if(error)throw new Error(error.message);setMessage('Scheduled. It is ready to go live.');await load()}catch(e){setMessage(e.message||'Could not schedule.')}finally{setBusy(false)}}
  return <main className="publish-workspace"><style>{`
    .publish-workspace{max-width:1160px;margin:0 auto;color:var(--text);font-family:var(--sans)}
    .pub-intro{padding:4px 0 26px}.pub-eyebrow{font-size:8px;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#a99773}.pub-title{margin:7px 0 0;font-family:var(--display);font-size:clamp(38px,5.2vw,62px);line-height:.93;letter-spacing:-.045em}.pub-copy{margin:10px 0 0;max-width:62ch;color:var(--text-muted);font-size:13px;line-height:1.6}
    .pub-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:2px}.pub-stat{padding:15px;border:1px solid var(--border);border-radius:14px;background:linear-gradient(180deg,rgba(255,255,255,.025),rgba(255,255,255,.01))}.pub-stat b{font-size:25px;letter-spacing:-.04em}.pub-stat span{display:block;margin-top:5px;color:var(--text-subtle);font-size:8px;letter-spacing:.13em;text-transform:uppercase}
    .pub-grid{display:grid;grid-template-columns:1.08fr .92fr;gap:16px;margin-top:16px}.pub-card{min-width:0;padding:19px;border:1px solid var(--border);border-radius:18px;background:linear-gradient(180deg,rgba(255,255,255,.026),rgba(255,255,255,.01))}.pub-label{font-size:8px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:var(--text-subtle)}.pub-card h2{margin:7px 0 0;font-family:var(--display);font-size:25px;line-height:1.04;letter-spacing:-.035em}.pub-muted{margin-top:6px;color:var(--text-muted);font-size:10px;line-height:1.5}.pub-list{display:grid;gap:7px;margin-top:14px;max-height:480px;overflow:auto}.pub-item{width:100%;text-align:left;padding:13px 14px;border:1px solid var(--border);border-radius:13px;background:#121419;color:var(--text);cursor:pointer;transition:.16s ease}.pub-item:hover{transform:translateY(-1px);border-color:rgba(255,255,255,.15)}.pub-item.active{border-color:rgba(216,195,154,.4);background:rgba(216,195,154,.075)}.pub-item strong{display:block;font-size:12px;line-height:1.35}.pub-item span{display:block;margin-top:5px;color:var(--text-subtle);font-size:9px}.pub-detail{margin-top:14px;padding:14px;border:1px solid rgba(216,195,154,.2);border-radius:13px;background:rgba(216,195,154,.055)}.pub-detail strong{font-size:14px}.pub-detail p{margin-top:5px;color:var(--text-muted);font-size:10px;line-height:1.5}
    .pub-form{margin-top:16px;padding-top:15px;border-top:1px solid var(--border)}.pub-form label{display:block;margin-top:12px;font-size:8px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:var(--text-subtle)}.pub-field{width:100%;margin-top:6px;min-height:43px;padding:10px 11px;border:1px solid var(--border);border-radius:10px;background:#0d0f13;color:var(--text);font:inherit;font-size:11px}.pub-btn{width:100%;min-height:46px;margin-top:14px;border:1px solid #efe8da;border-radius:10px;background:#efe8da;color:#171614;font:inherit;font-size:10px;font-weight:900;cursor:pointer}.pub-btn:disabled{opacity:.5;cursor:default}.pub-message{margin-top:10px;color:var(--text-muted);font-size:10px;line-height:1.45}.pub-error{margin-top:10px;padding:10px;border-radius:10px;background:rgba(150,70,70,.11);color:#d6aaaa;font-size:10px}.pub-link{display:inline-flex;margin-top:12px;color:var(--text);font-size:10px;font-weight:850;text-decoration:none}.pub-link:hover{color:#d6c29a}
    @media(max-width:860px){.pub-grid{grid-template-columns:1fr}}@media(max-width:560px){.pub-stats{grid-template-columns:1fr}.pub-card{padding:16px}}
  `}</style>
  <header className="pub-intro"><div className="pub-eyebrow">Publish</div><h1 className="pub-title">Choose what goes into the world.</h1><p className="pub-copy">Only finished work belongs here. Pick the piece, choose when it should appear, and let the publishing queue do the rest.</p></header>
  <section className="pub-stats"><div className="pub-stat"><b>{rows.length}</b><span>Ready to publish</span></div><div className="pub-stat"><b>{ready}</b><span>Waiting for a date</span></div><div className="pub-stat"><b>{scheduled}</b><span>Scheduled</span></div></section>
  <div className="pub-grid">
   <section className="pub-card"><div className="pub-label">Your finished work</div><h2>Pick a piece</h2><p className="pub-muted">Everything here has come through production. Select the one you want to put live next.</p><div className="pub-list">{rows.length?rows.map(r=><button key={r.id} className={`pub-item${selectedId===r.id?' active':''}`} onClick={()=>setSelectedId(r.id)}><strong>{r.title||'Untitled piece'}</strong><span>{r.platform||'Channel'} · {r.status||'Draft'}{r.scheduled_at?` · ${new Date(r.scheduled_at).toLocaleString('en-GB')}`:''}</span></button>):<div className="pub-muted">Nothing is waiting to go live yet. Finish a piece in Make first.</div>}</div>{selected?<div className="pub-detail"><strong>{selected.title||'Selected piece'}</strong><p>{selected.platform||'Channel'} · Current status: {selected.status||'draft'}</p></div>:null}</section>
   <section className="pub-card"><div className="pub-label">Your launch decision</div><h2>When should it go live?</h2><p className="pub-muted">Choose a moment. The rest stays attached to the piece.</p>{selected?<div className="pub-form"><label>Date<input className="pub-field" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input className="pub-field" type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button className="pub-btn" disabled={busy} onClick={schedule}>{busy?'Scheduling…':'Schedule it →'}</button>{selected.last_error?<div className="pub-error">{selected.last_error}</div>:null}<div className="pub-message">{message||'Ready when you are.'}</div><a className="pub-link" href="/content/measurement">After it goes live, record the result →</a></div>:<div className="pub-muted" style={{marginTop:18}}>Select a finished piece to choose its launch time.</div>}</section>
  </div>
 </main>;
}
