import React, { useMemo } from 'react';
import EnterpriseShell from './EnterpriseShell.jsx';
import CreateWorkspace from './CreateWorkspace.jsx';
import ProfileChannelsWorkspace from './ProfileChannelsWorkspace.jsx';
import CanonicalProductionWorkspace from './CanonicalProductionWorkspace.jsx';
import CanonicalPublishWorkspace from './CanonicalPublishWorkspace.jsx';
import CanonicalMeasureWorkspace from './CanonicalMeasureWorkspace.jsx';
import { CreatorsStaged } from './TrackBStagedSurfaces.jsx';

const STAGES = [
  ['remake', 'Create', 'Find a strong idea and make it yours.'],
  ['creators', 'Voices', 'Choose who brings it to life.'],
  ['profiles', 'Channels', 'Choose where it should win.'],
  ['production', 'Make', 'Turn the package into finished work.'],
  ['publish', 'Publish', 'Put approved work into the world.'],
  ['measurement', 'Learn', 'See what worked and use it.'],
];
const NEXT={remake:['creators','Choose a voice'],creators:['profiles','Choose a channel'],profiles:['production','Make the work'],production:['publish','Publish it'],publish:['measurement','See the result'],measurement:['remake','Use the learning']};
function stageFor(pathname){const value=pathname.match(/^\/content(?:\/([^/]+))?/)?.[1]||'remake';return STAGES.some(([id])=>id===value)?value:'remake';}
function Workspace({stage}){switch(stage){case'remake':return <CreateWorkspace/>;case'creators':return <CreatorsStaged stage={0} onAdvance={()=>{window.location.href='/content/profiles'}}/>;case'profiles':return <ProfileChannelsWorkspace/>;case'production':return <CanonicalProductionWorkspace/>;case'publish':return <CanonicalPublishWorkspace/>;case'measurement':return <CanonicalMeasureWorkspace/>;default:return null}}
export default function ContentWorkspaceShell(){const stage=useMemo(()=>stageFor(window.location.pathname),[]);const item=STAGES.find(([id])=>id===stage)||STAGES[0];const next=NEXT[stage]||NEXT.remake;return <EnterpriseShell active={stage==='remake'?'content':stage} eyebrow="Create"><main className="studio-shell"><style>{`.studio-shell{min-width:0;max-width:1240px;margin:0 auto}.studio-back{display:inline-flex;align-items:center;gap:7px;color:var(--text-muted);font-size:10px;font-weight:800;text-decoration:none;margin-bottom:18px}.studio-back:hover{color:var(--text)}.studio-nav{display:flex;gap:4px;padding:4px;margin-bottom:22px;border:1px solid var(--border);border-radius:13px;background:rgba(255,255,255,.02);overflow:auto;scrollbar-width:none}.studio-nav::-webkit-scrollbar{display:none}.studio-nav a{position:relative;min-width:110px;flex:1;padding:10px 11px;border-radius:9px;color:var(--text-muted);text-decoration:none;font-size:10px;font-weight:850;white-space:nowrap}.studio-nav a:hover{background:rgba(255,255,255,.04);color:var(--text)}.studio-nav a.active{background:rgba(196,180,154,.10);color:var(--text)}.studio-nav a.active:after{content:'';position:absolute;left:11px;right:11px;bottom:4px;height:1px;background:var(--track-b)}.studio-nav small{display:block;margin-top:3px;color:var(--text-subtle);font-size:8px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.studio-title{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:20px}.studio-title h1{margin:6px 0 0;font-size:clamp(32px,4.5vw,53px);line-height:.95;letter-spacing:-.06em}.studio-title p{margin:8px 0 0;color:var(--text-muted);font-size:12px;line-height:1.5}.studio-k{font-size:8px;font-weight:900;letter-spacing:.15em;text-transform:uppercase;color:var(--track-b)}.studio-next{text-align:right}.studio-next span{display:block;font-size:8px;letter-spacing:.13em;text-transform:uppercase;color:var(--text-subtle)}.studio-next a{display:inline-flex;gap:6px;margin-top:5px;color:var(--text);font-size:10px;font-weight:900;text-decoration:none}.studio-next b{color:var(--track-b)}@media(max-width:760px){.studio-title{display:block}.studio-next{display:none}.studio-nav a{min-width:96px}.studio-nav small{display:none}}
`}</style><a href="/" className="studio-back">← Home</a><nav className="studio-nav" aria-label="Content workflow">{STAGES.map(([id,label,description])=><a key={id} href={`/content/${id}`} className={stage===id?'active':''}>{label}<small>{description}</small></a>)}</nav><header className="studio-title"><div><div className="studio-k">{stage==='remake'?'Create a new piece':'Content workspace'}</div><h1>{item[1]}</h1><p>{item[2]}</p></div><div className="studio-next"><span>Next</span><a href={`/content/${next[0]}`}>{next[1]} <b>→</b></a></div></header><Workspace stage={stage}/></main></EnterpriseShell>}
