import React, { useMemo, useState } from "react";
import { CREATIVE_GOALS, CREATIVE_FORMATS, CREATIVE_HOOKS, CREATIVE_ANGLES, CREATOR_ROSTER, buildCreativeMatrix, creatorLabel, generateWinnerVariants, verdictFromMetrics } from "./creativeEngine";
import "./creativeEngine.css";

const STORAGE_KEY = "caig_creative_tests";
const load = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; } };
const save = v => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(v)); } catch {} };
function MetricInput({ label, value, onChange }) { return <label className="ce-label">{label}<input type="number" min="0" step="any" value={value ?? ""} onChange={e => onChange(e.target.value)} /></label>; }

export default function CreativeEngine({ toast_ }) {
  const [tests, setTests] = useState(load);
  const [product, setProduct] = useState(""); const [brand, setBrand] = useState("");
  const [objective, setObjective] = useState("attention"); const [platform, setPlatform] = useState("TikTok");
  const [creatorIds, setCreatorIds] = useState(["cara", "lila", "cara_lila"]);
  const [hookIds, setHookIds] = useState(["specific_claim", "curiosity", "proof"]);
  const [angleIds, setAngleIds] = useState(["real_life", "proof", "routine"]);
  const [formatIds, setFormatIds] = useState(["hook_reel", "ugc_demo", "creator_duo"]);
  const [selected, setSelected] = useState(null); const [tab, setTab] = useState("matrix");
  const persist = next => { setTests(next); save(next); };
  const toggle = (setter, id) => setter(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  const matrixCount = creatorIds.length * hookIds.length * angleIds.length;
  const stats = useMemo(() => ({ total: tests.length, measuring: tests.filter(t => ["published","measuring"].includes(t.status)).length, winners: tests.filter(t => t.status === "winner").length, promising: tests.filter(t => t.status === "promising").length }), [tests]);
  const generateMatrix = () => { if (!product.trim()) { toast_("Add a product first", "warn"); return; } const rows = buildCreativeMatrix({ product, brand, creatorIds, hookIds, angleIds, formats: formatIds.length ? formatIds : ["hook_reel"] }).map(t => ({ ...t, platform })); persist([...rows, ...tests]); toast_(`${rows.length} creative tests created`, "ok"); };
  const update = (id, patch) => persist(tests.map(t => t.id === id ? { ...t, ...patch } : t));
  const markPublished = t => update(t.id, { status: "measuring", publishedAt: new Date().toISOString() });
  const score = t => {
    const peers = tests.filter(x => x.platform === t.platform && x.id !== t.id);
    const mean = (field, fn = v => Number(v)) => { const vals = peers.map(x => fn(x.metrics?.[field])).filter(Number.isFinite); return vals.length ? vals.reduce((a,b)=>a+b,0)/vals.length : null; };
    const result = verdictFromMetrics(t.metrics, { viewRate: mean("views", v => t.metrics.impressions > 0 ? Number(v)/Number(t.metrics.impressions) : NaN), completionRate: mean("completionRate"), shareRate: mean("shares", v => t.metrics.views > 0 ? Number(v)/Number(t.metrics.views) : NaN), clickRate: mean("clicks", v => t.metrics.impressions > 0 ? Number(v)/Number(t.metrics.impressions) : NaN) });
    update(t.id, { status: result.verdict, verdict: result, reviewedAt: new Date().toISOString() }); setSelected(null);
  };
  const makeVariants = t => { const variants = generateWinnerVariants(t,5).map(v=>({...v,platform:t.platform})); persist([...variants,...tests]); toast_("5 winner variations added", "ok"); };
  return <div className="ce-shell fu">
    <section className="ce-card">
      <div className="ce-section"><div><div className="ce-title">Creative Engine</div><div className="ce-sub">Research the idea → build the matrix → produce → publish → measure → double down on winners.</div></div><div className="ce-badge ce-measuring">Cara & Lila included</div></div>
      <div className="ce-callout" style={{marginBottom:14}}><strong>Core idea:</strong> I am not selling “AI UGC.” I am building a repeatable creative-testing loop. Cara, Lila and Cara + Lila are the owned proof roster; products can be placed naturally into their content so the same engine can create organic social proof for Cornerstone.</div>
      <div className="ce-form">
        <label className="ce-label">Brand<input value={brand} onChange={e=>setBrand(e.target.value)} placeholder="e.g. Cornerstone AI Group" /></label>
        <label className="ce-label">Product<input value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. skincare, coffee, dress, gym product" /></label>
        <label className="ce-label">Objective<select value={objective} onChange={e=>setObjective(e.target.value)}>{CREATIVE_GOALS.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>
        <label className="ce-label">Primary platform<select value={platform} onChange={e=>setPlatform(e.target.value)}>{["TikTok","Instagram Reels","YouTube Shorts","Facebook Reels","Instagram","YouTube"].map(x=><option key={x}>{x}</option>)}</select></label>
      </div>
      <div style={{marginTop:18}}><div className="ce-label">Creators</div><div className="ce-grid">{CREATOR_ROSTER.map(c=><button key={c.id} className={`ce-chip${creatorIds.includes(c.id)?" on":""}`} onClick={()=>toggle(setCreatorIds,c.id)}><b>{c.label}</b><span>{c.role}</span></button>)}</div></div>
      <div style={{marginTop:14}}><div className="ce-label">Hooks</div><div className="ce-grid">{CREATIVE_HOOKS.map(h=><button key={h.id} className={`ce-chip${hookIds.includes(h.id)?" on":""}`} onClick={()=>toggle(setHookIds,h.id)}><b>{h.label}</b><span>{h.template}</span></button>)}</div></div>
      <div style={{marginTop:14}}><div className="ce-label">Angles</div><div className="ce-grid">{CREATIVE_ANGLES.map(a=><button key={a.id} className={`ce-chip${angleIds.includes(a.id)?" on":""}`} onClick={()=>toggle(setAngleIds,a.id)}><b>{a.label}</b><span>{a.instruction}</span></button>)}</div></div>
      <div style={{marginTop:14}}><div className="ce-label">Formats</div><div className="ce-grid">{CREATIVE_FORMATS.map(f=><button key={f.id} className={`ce-chip${formatIds.includes(f.id)?" on":""}`} onClick={()=>toggle(setFormatIds,f.id)}><b>{f.label}</b><span>{f.bestFor.join(" · ")}</span></button>)}</div></div>
      <div className="ce-actions"><button className="btn btn-amber" onClick={generateMatrix}>Build {matrixCount} tests</button><button className="btn btn-dim" onClick={()=>{setProduct("");setBrand("")}}>Clear</button></div>
    </section>
    <aside className="ce-card"><div className="ce-title">Engine scoreboard</div><div className="ce-sub">The system gets smarter from performance, not from more generation alone.</div><div className="ce-kpi-grid" style={{marginTop:14}}><div className="ce-kpi"><div className="n">{stats.total}</div><div className="l">Tests</div></div><div className="ce-kpi"><div className="n">{stats.measuring}</div><div className="l">Measuring</div></div><div className="ce-kpi"><div className="n">{stats.winners}</div><div className="l">Winners</div></div><div className="ce-kpi"><div className="n">{stats.promising}</div><div className="l">Promising</div></div></div><div className="ce-callout" style={{marginTop:14}}><strong>Winner rule:</strong> when a concept materially beats the current baseline, make five variations. Keep the winning angle; change the hook, scene, pacing or creator treatment.</div><div className="ce-tabs" style={{marginTop:14}}>{["matrix","winners","learning"].map(x=><button key={x} className={`ce-tab${tab===x?" on":""}`} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></aside>
    <section className="ce-card" style={{gridColumn:"1 / -1"}}>
      {tab === "matrix" && <><div className="ce-section"><div><div className="ce-title">Creative matrix</div><div className="ce-sub">Each row is a hypothesis: creator × hook × angle × format.</div></div></div>{tests.length===0?<div className="ce-empty">Build your first matrix above.</div>:<div className="ce-list">{tests.slice(0,100).map(t=><div className="ce-row" key={t.id}><div className="ce-row-main"><div className="ce-row-title">{t.product} · {creatorLabel(t.creator)} · {t.hook} · {t.angle}</div><div className="ce-row-meta">{t.platform} · {t.format} · objective: {t.objective}</div></div><span className={`ce-badge ce-${t.status === "winner" ? "winner" : t.status === "promising" ? "promising" : t.status === "loser" ? "loser" : "measuring"}`}>{t.status}</span><div className="ce-row-actions"><button className="btn btn-dim" onClick={()=>setSelected(t)}>Metrics</button>{t.status==="idea"&&<button className="btn btn-dim" onClick={()=>markPublished(t)}>Published</button>}{t.status==="measuring"&&<button className="btn btn-dim" onClick={()=>setSelected(t)}>Score</button>}{t.status==="winner"&&<button className="btn btn-green" onClick={()=>makeVariants(t)}>5 variations</button>}</div></div>)}</div>}</>}
      {tab === "winners" && <div><div className="ce-title">Winning creative</div><div className="ce-sub">Concepts worth multiplying across creators, hooks and formats.</div><div style={{marginTop:12}} className="ce-list">{tests.filter(t=>t.status==="winner").map(t=><div className="ce-row" key={t.id}><div className="ce-row-main"><div className="ce-row-title">{t.product} · {creatorLabel(t.creator)} · {t.hook}</div><div className="ce-row-meta">{t.platform} · {t.format} · {t.angle}</div></div><button className="btn btn-green" onClick={()=>makeVariants(t)}>Make 5 variations</button></div>)}</div>{tests.filter(t=>t.status==="winner").length===0&&<div className="ce-empty" style={{marginTop:12}}>No winners yet. Publish, add metrics and score.</div>}</div>}
      {tab === "learning" && <div><div className="ce-title">Learning log</div><div className="ce-sub">Every test should leave a reusable lesson.</div><div style={{marginTop:12}} className="ce-list">{tests.slice(0,50).map(t=><div className="ce-row" key={t.id}><div className="ce-row-main"><div className="ce-row-title">{t.product} · {creatorLabel(t.creator)} · {t.hook} · {t.status}</div><div className="ce-row-meta">{t.notes||"No learning note yet."}</div></div><button className="btn btn-dim" onClick={()=>setSelected(t)}>Edit metrics</button></div>)}</div></div>}
    </section>
    {selected&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.68)",zIndex:120,display:"flex",alignItems:"center",justifyContent:"center",padding:18}} onClick={()=>setSelected(null)}><div className="ce-card" style={{width:"min(680px,100%)",maxHeight:"90vh",overflow:"auto"}} onClick={e=>e.stopPropagation()}><div className="ce-section"><div><div className="ce-title">Metrics · {creatorLabel(selected.creator)}</div><div className="ce-sub">Enter platform results, then score the creative against the current baseline.</div></div><button className="btn btn-ghost" onClick={()=>setSelected(null)}>Close</button></div><div className="ce-form"><MetricInput label="Impressions" value={selected.metrics.impressions} onChange={v=>update(selected.id,{metrics:{...selected.metrics,impressions:v===""?null:Number(v)}})} /><MetricInput label="Views" value={selected.metrics.views} onChange={v=>update(selected.id,{metrics:{...selected.metrics,views:v===""?null:Number(v)}})} /><MetricInput label="Completion %" value={selected.metrics.completionRate} onChange={v=>update(selected.id,{metrics:{...selected.metrics,completionRate:v===""?null:Number(v)}})} /><MetricInput label="Shares" value={selected.metrics.shares} onChange={v=>update(selected.id,{metrics:{...selected.metrics,shares:v===""?null:Number(v)}})} /><MetricInput label="Saves" value={selected.metrics.saves} onChange={v=>update(selected.id,{metrics:{...selected.metrics,saves:v===""?null:Number(v)}})} /><MetricInput label="Clicks" value={selected.metrics.clicks} onChange={v=>update(selected.id,{metrics:{...selected.metrics,clicks:v===""?null:Number(v)}})} /><MetricInput label="Conversions" value={selected.metrics.conversions} onChange={v=>update(selected.id,{metrics:{...selected.metrics,conversions:v===""?null:Number(v)}})} /><label className="ce-label full">Learning note<textarea value={selected.notes} onChange={e=>update(selected.id,{notes:e.target.value})} placeholder="What did this teach me?" /></label></div><div className="ce-actions"><button className="btn btn-amber" onClick={()=>score(selected)}>Score against baseline</button></div></div></div>}
  </div>;
}
