import React, { useEffect, useMemo, useState } from 'react'
import { supabase } from './supabase'

const PERSONAS=[
 {id:'cara',name:'Cara',tone:'Direct, dry, disciplined',tag:'Sharper takes'},
 {id:'lila',name:'Lila',tone:'Warm, observant, understated',tag:'Quietly personal'},
 {id:'cara_lila',name:'Cara + Lila',tone:'Contrast, chemistry, two voices',tag:'Built for interaction'},
]
const PLATFORMS=['TikTok','Instagram','YouTube','TikTok Shop','Affiliate','Fanvue']
const OBJECTIVES=['Create content','Grow audience','Test monetisation','Drive clicks / sales','Build a repeatable series']
const FORMATS=['Personal moment','POV / relatable','Quick take','Micro-story','GRWM','Day in the life','Photo slideshow','Reaction','Product-led demo','Story + recommendation']
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms))
const parse=(value)=>{if(typeof value!=='string')return value||{};const text=value.replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/<analysis>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,'').replace(/```json|```/gi,'').replace(/<\|im_end\|>|<\|endoftext\|>/gi,'').trim();try{return JSON.parse(text)}catch{}return{raw:text}}
const arr=(v)=>Array.isArray(v)?v:[]
async function getUser(){const{data,error}=await supabase.auth.getUser();if(error||!data?.user)throw new Error('Please sign in again.');return data.user}
async function jobStatus(id){const{data,error}=await supabase.from('local_ai_jobs').select('id,status,result,error_message').eq('id',id).maybeSingle();if(error)throw error;if(!data)throw new Error('Creator job disappeared.');return data}
async function waitJob(id,setMessage,label){const until=Date.now()+45*60*1000;let last='';while(Date.now()<until){const job=await jobStatus(id);if(job.status!==last){last=job.status;setMessage(job.status==='processing'?`${label} is working…`:`${label} is ${job.status}…`)}if(job.status==='completed')return job;if(job.status==='error')throw new Error(job.error_message||`${label} failed.`);await sleep(2500)}throw new Error(`${label} took too long. Check System.`)}

export default function CreatorGrowthWorkspaceFinal({onAdvance}={}){
 const[persona,setPersona]=useState('cara'),[platform,setPlatform]=useState('TikTok'),[objective,setObjective]=useState('Create content'),[format,setFormat]=useState('Personal moment'),[direction,setDirection]=useState(''),[referenceUrl,setReferenceUrl]=useState(''),[offer,setOffer]=useState(''),[result,setResult]=useState(null),[jobs,setJobs]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const selected=PERSONAS.find(x=>x.id===persona)||PERSONAS[0]
 const pNeedsOffer=platform==='TikTok Shop'||platform==='Affiliate'
 const packageData=result?.production_package||result?.package||result||{}
 const brief=result?.operator_brief||{}
 const titles=useMemo(()=>arr(packageData.titles||packageData.title_options),[packageData])
 const hooks=useMemo(()=>arr(packageData.hooks||packageData.hook_options),[packageData])
 const imagePrompts=useMemo(()=>arr(packageData.image_prompts||packageData.visual_image_prompts),[packageData])
 const research=useMemo(()=>arr(result?.creator_research||packageData.creator_research||packageData.comparable_patterns),[result,packageData])
 const visual=useMemo(()=>arr(packageData.visual_direction||packageData.shot_list||packageData.visual_timeline),[packageData])

 async function load(){const u=await getUser();const{data,error:e}=await supabase.from('local_ai_jobs').select('id,title,status,created_at,persona_id,options,result').eq('owner_id',u.id).eq('job_type','content_engine').eq('options->>workspace_id','creator_growth').order('created_at',{ascending:false}).limit(24);if(e)throw e;setJobs(data||[])}
 useEffect(()=>{load().catch(e=>setError(e?.message||String(e)))},[])

 async function inspectReference(u){
  if(!referenceUrl.trim())return null
  let parsed;try{parsed=new URL(referenceUrl.trim())}catch{throw new Error('Reference URL is not valid.')}
  const host=parsed.hostname.toLowerCase().replace(/^www\./,'')
  if(!['youtube.com','m.youtube.com','youtu.be','youtube-nocookie.com','tiktok.com','instagram.com'].includes(host))throw new Error('Reference analysis supports public YouTube, TikTok and Instagram URLs.')
  setMessage('Acquiring the reference…')
  const{data,error:e}=await supabase.from('local_ai_jobs').insert({owner_id:u.id,title:`${selected.name} reference · ${platform}`,job_type:'creator_source_ingestion',model:'mlx-community/Qwen3-8B-4bit',persona_id:persona,system_prompt:'Acquire one public creator reference for local media evidence inspection. Never claim analysis before the media is processed.',user_prompt:`Acquire this public ${host} creator reference for ${selected.name}: ${referenceUrl.trim()}`,options:{source_url:referenceUrl.trim(),original_url:referenceUrl.trim(),research_domain:'TRACK_B_CREATOR_GROWTH',workspace_id:'creator_growth',platform,creator_id:persona},status:'queued',production_status:'creator_source_queued'}).select('id').single();if(e||!data?.id)throw e||new Error('Could not queue the creator reference.')
  const acquired=await waitJob(data.id,setMessage,'Reference acquisition');const acquisition=parse(acquired.result);if(!acquisition.media_job_id)throw new Error('Reference acquired without a media inspection job.')
  const mediaJob=await waitJob(acquisition.media_job_id,setMessage,'Reference inspection');const media=parse(mediaJob.result);if(!media.text_analysis_job_id)throw new Error('Reference inspection completed without source intelligence.')
  const analysisJob=await waitJob(media.text_analysis_job_id,setMessage,'Reference intelligence');return{acquisition,media,analysis:parse(analysisJob.result)}
 }

 async function build(){setBusy(true);setError('');setMessage('Starting creator intelligence…');setResult(null);try{const u=await getUser();const source=await inspectReference(u);setMessage('Building the creator experiment…');const prompt=[
  `CREATOR: ${selected.name}`,`PERSONA_ID: ${persona}`,`PLATFORM: ${platform}`,`OBJECTIVE: ${objective}`,`FORMAT: ${format}`,`PRODUCT / OFFER: ${offer.trim()||'None'}`,`REFERENCE URL: ${referenceUrl.trim()||'None'}`,`DIRECTION: ${direction.trim()||'Choose the strongest evidence-backed opportunity.'}`,'',
  'This is a creator-business decision, not a generic idea request.',
  'Use the selected creator bible as hard identity context.',
  'Use current public creator research where available. Never invent follower counts, views, sales, comments, audience reactions, prices, commissions, product facts or revenue.',
  source?`INSPECTED REFERENCE EVIDENCE:\n${JSON.stringify(source.analysis)}\nThe reference is research only. Abstract the mechanism. Do not copy wording, creator identity, branding, scenes, footage or distinctive execution.`:'No reference was supplied. Work from creator context and current public evidence.',
  `PLATFORM STRATEGY: ${platform==='TikTok'?'first-frame hook, native pacing, retention loop and repeatability.':platform==='Instagram'?'Reels/carousels, shareability, profile intent and visual identity.':platform==='YouTube'?'standalone depth, stronger narrative and Shorts derivatives.':platform==='TikTok Shop'?'useful product-led content with a natural purchase moment and compliant claims.':platform==='Affiliate'?'trust-first recommendation content with a natural click path and disclosure.':'creator-safe paid-content teasers with a clear reason to subscribe.'}`,
  'Return operator-first JSON with operator_brief, creator_research and production_package.',
  'operator_brief: finding, evidence_status, evidence_quality, source_inspection, mechanism, why, recommended_subject, recommended_angle, next_action, confidence, limitations.',
  'creator_research: comparable public patterns/accounts, platform, observable signal, transferable mechanism, adapt/ignore decision, source URL where available.',
  'production_package: concept, 8 title/headline options, 5 hooks, opening beat, actual script/spoken lines, shot list, visual direction, image_prompts, caption, CTA, hashtags, publication plan, repurposing plan, monetisation_route, monetisation_test, KPI, winner_rule, follow_up_ideas, originality_plan.',
  'TikTok Shop: never invent product claims, discounts, commissions, reviews or results.',
  'Affiliate: never invent commissions, prices, product facts, reviews or results.',
  'Fanvue: keep content appropriate to the owned creator asset. Make the paid value proposition clear without inventing audience behaviour or revenue.',
  'Return JSON only.',
 ].join('\n')
 const{data,error:e}=await supabase.from('local_ai_jobs').insert({owner_id:u.id,title:`${selected.name} · ${platform} · ${format}`,job_type:'content_engine',model:'mlx-community/Qwen3-8B-4bit',persona_id:persona,system_prompt:'You are Cornerstone Track B Creator Growth Director. Protect creator identity. Build complete, publishable, platform-native creator work and measurable monetisation experiments. Never invent facts or metrics. Return operator-first JSON.',user_prompt:prompt,options:{research:true,max_tokens:6500,temperature:.42,research_domain:'TRACK_B_CREATOR_GROWTH',workspace_id:'creator_growth',creator_id:persona,platform,objective,format,reference_url:referenceUrl.trim()||null,offer:offer.trim()||null,source_evidence:source},status:'queued',production_status:'creator_package_queued'}).select('id').single();if(e||!data?.id)throw e||new Error('Could not queue creator package.');const completed=await waitJob(data.id,setMessage,'Creator experiment');setResult(parse(completed.result));setMessage('Creator experiment ready.');await load()}catch(e){setError(e?.message||String(e));setMessage('')}finally{setBusy(false)}}

 return <main className="cg-final"><style>{`
 .cg-final{color:var(--text)}.cg-head{padding:8px 0 28px;border-bottom:1px solid var(--border)}.cg-kicker{font-size:10px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:var(--accent)}.cg-title{margin:8px 0 0;font-size:clamp(40px,5.6vw,72px);line-height:.92;letter-spacing:-.06em;max-width:900px}.cg-copy{margin:13px 0 0;max-width:800px;color:var(--text-muted);font-size:14px;line-height:1.65}
 .cg-people{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0 14px}.cg-person{position:relative;min-height:145px;padding:18px;border:1px solid var(--border);border-radius:14px;background:var(--surface);color:var(--text);text-align:left;cursor:pointer}.cg-person.active{border-color:var(--accent)}.cg-person:before{content:"";position:absolute;left:0;top:0;width:100%;height:3px;background:var(--border-strong)}.cg-person.active:before{background:var(--accent)}.cg-num{font-size:9px;color:var(--text-subtle);letter-spacing:.12em}.cg-name{margin-top:23px;font-size:29px;font-weight:850;letter-spacing:-.05em}.cg-tag{margin-top:6px;font-size:9px;color:var(--text-muted)}.cg-tone{margin-top:10px;font-size:10px;color:var(--text-subtle)}
 .cg-work{display:grid;grid-template-columns:1.12fr .88fr;gap:14px}.cg-card{padding:20px;border:1px solid var(--border);border-radius:14px;background:var(--surface)}.cg-label{font-size:9px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:var(--text-subtle)}.cg-card h2{margin:7px 0 0;font-size:24px;letter-spacing:-.04em}.cg-fields{display:grid;grid-template-columns:1fr 1fr;gap:11px;margin-top:16px}.cg-field{display:grid;gap:6px}.cg-field.full{grid-column:1/-1}.cg-field>span{font-size:9px;font-weight:850;letter-spacing:.1em;text-transform:uppercase;color:var(--text-subtle)}.cg-field input,.cg-field select,.cg-field textarea{width:100%;padding:11px 12px;border:1px solid var(--border-strong);border-radius:8px;background:var(--panel-2);color:var(--text);font:inherit;font-size:11px;outline:none}.cg-field textarea{min-height:105px;resize:vertical;line-height:1.5}.cg-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-top:14px}.cg-btn{min-height:44px;padding:0 15px;border:0;border-radius:8px;background:var(--accent);color:#1a0f0c;font-size:11px;font-weight:900;cursor:pointer}.cg-btn.alt{background:transparent;border:1px solid var(--line-2);color:var(--text)}.cg-btn:disabled{opacity:.45}.cg-status{margin-top:9px;font-size:10px;color:var(--text-muted)}.cg-error{margin-top:9px;color:var(--bad);font-size:11px}
 .cg-side{background:var(--panel-2)}.cg-side h3{margin:7px 0 0;font-size:32px;letter-spacing:-.05em}.cg-side p{margin:9px 0 0;color:var(--text-2);font-size:11px;line-height:1.65}.cg-chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:16px}.cg-chip{padding:5px 8px;border:1px solid var(--border);border-radius:999px;background:var(--surface);font-size:9px;color:var(--text-muted)}
 .cg-result{margin-top:14px;display:grid;gap:12px}.cg-result-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.cg-r{padding:17px;border:1px solid var(--border);border-radius:12px;background:var(--surface)}.cg-r p{margin-top:8px;color:var(--text-2);font-size:12px;line-height:1.55;white-space:pre-wrap}.cg-items{display:grid;gap:7px;margin-top:10px}.cg-item{padding:10px 11px;border-left:2px solid var(--accent);background:var(--panel-2);font-size:11px;line-height:1.45}.cg-research{display:grid;gap:7px;margin-top:10px}.cg-research div{padding:10px 11px;border:1px solid var(--border);border-radius:8px;background:var(--panel-2);font-size:10px}.cg-research span{display:block;margin-top:4px;color:var(--text-3);line-height:1.4}.cg-json{margin:0;max-height:420px;overflow:auto;white-space:pre-wrap;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--text-2)}
 .cg-history{margin-top:18px;padding-top:18px;border-top:1px solid var(--border)}.cg-history-head{display:flex;justify-content:space-between;gap:10px}.cg-history-head strong{font-size:13px}.cg-history-head span{font-size:9px;color:var(--text-subtle)}.cg-jobs{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.cg-job{padding:11px;border:1px solid var(--border);border-radius:9px;background:var(--surface)}.cg-job strong{font-size:10px}.cg-job span{display:block;margin-top:4px;color:var(--text-muted);font-size:9px}
 @media(max-width:880px){.cg-people,.cg-work,.cg-result-grid{grid-template-columns:1fr}.cg-fields{grid-template-columns:1fr}.cg-field.full{grid-column:auto}.cg-jobs{grid-template-columns:1fr}}
 `}</style>
 <header className="cg-head"><div className="cg-kicker">Creator Growth Engine</div><h1 className="cg-title">Give Cara and Lila the whole business.</h1><p className="cg-copy">Create the content, study references, grow the audience and test the money layer across TikTok, Instagram, YouTube, TikTok Shop, affiliates and Fanvue. Cara and Lila are the assets. Cornerstone is the operating system around them.</p></header>
 <section className="cg-people">{PERSONAS.map((p,i)=><button key={p.id} className={`cg-person${persona===p.id?' active':''}`} onClick={()=>setPersona(p.id)}><div className="cg-num">0{i+1}</div><div className="cg-name">{p.name}</div><div className="cg-tag">{p.tag}</div><div className="cg-tone">{p.tone}</div></button>)}</section>
 <section className="cg-work"><div className="cg-card"><div className="cg-label">Experiment builder</div><h2>What should {selected.name} test next?</h2><div className="cg-fields">
 <label className="cg-field"><span>Platform</span><select value={platform} onChange={e=>setPlatform(e.target.value)}>{PLATFORMS.map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="cg-field"><span>Objective</span><select value={objective} onChange={e=>setObjective(e.target.value)}>{OBJECTIVES.map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="cg-field"><span>Format</span><select value={format} onChange={e=>setFormat(e.target.value)}>{FORMATS.map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="cg-field"><span>{pNeedsOffer?'Product / offer':'Reference URL'}</span><input value={pNeedsOffer?offer:referenceUrl} onChange={e=>pNeedsOffer?setOffer(e.target.value):setReferenceUrl(e.target.value)} placeholder={pNeedsOffer?'What product or offer are we testing?':'Optional public YouTube, TikTok or Instagram reference'} /></label>
 {pNeedsOffer?<label className="cg-field"><span>Reference URL</span><input value={referenceUrl} onChange={e=>setReferenceUrl(e.target.value)} placeholder="Optional example to study" /></label>:null}
 <label className="cg-field full"><span>Direction</span><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="A story, feeling, product, conversation, trend, offer or experiment worth owning…" /></label>
 </div><div className="cg-actions"><button className="cg-btn" onClick={build} disabled={busy}>{busy?'Building…':'Build creator experiment →'}</button><button className="cg-btn alt" onClick={()=>onAdvance?onAdvance():(window.location.href='/content/profiles')}>Continue to Channels →</button></div>{message?<div className="cg-status">{message}</div>:null}{error?<div className="cg-error">{error}</div>:null}</div>
 <aside className="cg-card cg-side"><div className="cg-label">Selected creator</div><h3>{selected.name}</h3><p>{selected.tone}. The same idea can be rebuilt differently for each platform rather than treating YouTube as the whole business.</p><div className="cg-chips"><span className="cg-chip">{platform}</span><span className="cg-chip">{objective}</span><span className="cg-chip">{format}</span>{pNeedsOffer?<span className="cg-chip">Monetisation</span>:null}</div><p>Reference analysis: {referenceUrl.trim()?'will inspect source media before building.':'optional.'}</p></aside></section>
 {result?<section className="cg-result"><div className="cg-result-grid"><article className="cg-r"><div className="cg-label">What Cornerstone found</div><p>{brief.finding||brief.mechanism||packageData.opportunity||packageData.concept?.why||'Creator opportunity extracted.'}</p></article><article className="cg-r"><div className="cg-label">Next action</div><p>{brief.next_action||brief.recommended_angle||packageData.next_experiment||'Make and measure the selected experiment.'}</p></article></div>
 {titles.length?<article className="cg-r"><div className="cg-label">Titles / headlines</div><div className="cg-items">{titles.slice(0,8).map((x,i)=><div className="cg-item" key={i}>{typeof x==='string'?x:x?.title||JSON.stringify(x)}</div>)}</div></article>:null}
 {hooks.length?<article className="cg-r"><div className="cg-label">Hooks</div><div className="cg-items">{hooks.slice(0,5).map((x,i)=><div className="cg-item" key={i}>{typeof x==='string'?x:x?.hook||JSON.stringify(x)}</div>)}</div></article>:null}
 {research.length?<article className="cg-r"><div className="cg-label">Current public research</div><div className="cg-research">{research.slice(0,6).map((x,i)=><div key={i}><strong>{x.account||x.name||x.title||x.source||`Pattern ${i+1}`}</strong><span>{x.signal||x.mechanism||x.observation||x.use||JSON.stringify(x)}</span></div>)}</div></article>:null}
 {visual.length?<article className="cg-r"><div className="cg-label">Visual direction</div><div className="cg-items">{visual.slice(0,8).map((x,i)=><div className="cg-item" key={i}>{typeof x==='string'?x:x?.shot||x?.scene||x?.direction||JSON.stringify(x)}</div>)}</div></article>:null}
 {imagePrompts.length?<article className="cg-r"><div className="cg-label">Image-generation prompts</div><div className="cg-items">{imagePrompts.slice(0,8).map((x,i)=><div className="cg-item" key={i}>{typeof x==='string'?x:x?.prompt||JSON.stringify(x)}</div>)}</div></article>:null}
 <article className="cg-r"><div className="cg-label">Full package</div><pre className="cg-json">{JSON.stringify(result,null,2)}</pre></article></section>:null}
 <section className="cg-history"><div className="cg-history-head"><strong>Recent creator work</strong><span>Persistent experiment history</span></div><div className="cg-jobs">{jobs.map(j=><div className="cg-job" key={j.id}><strong>{j.title}</strong><span>{j.persona_id} · {j.options?.platform||'platform'} · {j.status} · {new Date(j.created_at).toLocaleDateString('en-GB')}</span></div>)}{!jobs.length?<div className="cg-job"><strong>No creator experiments yet.</strong><span>Build one above.</span></div>:null}</div></section>
 </main>
}
