import React,{useEffect,useMemo,useState} from 'react'
import {supabase} from './supabase'

const CREATOR_OPTIONS=[
  {id:'cara',name:'Cara',tone:'Direct, dry, disciplined'},
  {id:'lila',name:'Lila',tone:'Warm, observant, understated'},
  {id:'cara_lila',name:'Cara + Lila',tone:'Contrast, chemistry, two voices'},
]
const PLATFORMS=['TikTok','Instagram','YouTube','Fanvue','Multi-platform']
const OBJECTIVES=['Content creation','TikTok Shop','Affiliate offers','Fanvue / subscriber content','Sponsorships','Audience growth']
const FORMATS=['POV / relatable','Story / confession','GRWM','Day in the life','Reaction','Product / UGC','Photo carousel','Talking-to-camera','Duo interaction']
const SOURCE_HOSTS=new Set(['youtube.com','m.youtube.com','youtu.be','youtube-nocookie.com','tiktok.com','instagram.com'])
const sleep=ms=>new Promise(r=>setTimeout(r,ms))
const clean=v=>String(v??'').trim()
function parseJson(text){const value=clean(text).replace(/```json|```/gi,'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/<analysis>[\s\S]*?<\/analysis>/gi,'').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi,'').replace(/<\|im_end\|>|<\|endoftext\|>/gi,'').trim();try{return JSON.parse(value)}catch{}const start=value.search(/[\[{]/);if(start<0)throw new Error('Cornerstone could not understand the returned creator package.');const open=value[start],close=open==='{'?'}':']';let depth=0,quoted=false,escaped=false;for(let i=start;i<value.length;i++){const c=value[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;continue}if(c==='"')quoted=true;else if(c===open)depth++;else if(c===close&&--depth===0)return JSON.parse(value.slice(start,i+1))}throw new Error('Cornerstone returned an incomplete creator package.')}
async function job(id,setMessage,label){const until=Date.now()+45*60*1000;let last='';while(Date.now()<until){const r=await fetch(`/api/queue-update?action=job_status&id=${encodeURIComponent(id)}`,{credentials:'same-origin',cache:'no-store'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Could not read job status.');if(b.status!==last){last=b.status;setMessage(b.status==='processing'?`${label} is working…`:`${label} is ${b.status}…`)}if(b.status==='completed')return b;if(b.status==='error')throw new Error(b.error_message||`${label} failed.`);await sleep(2500)}throw new Error(`${label} took too long. Check System.`)}
function normaliseSource(raw){const u=new URL(raw);const host=u.hostname.toLowerCase().replace(/^www\./,'');if(!SOURCE_HOSTS.has(host))throw new Error('Use a public YouTube, TikTok or Instagram URL.');return u.toString()}

export default function CreatorStudioWorkspace(){
 const[creator,setCreator]=useState('cara'),[platform,setPlatform]=useState('TikTok'),[objective,setObjective]=useState('Content creation'),[format,setFormat]=useState('POV / relatable'),[direction,setDirection]=useState(''),[url,setUrl]=useState(''),[learning,setLearning]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(null)
 useEffect(()=>{supabase.from('track_b_learning_recommendations').select('id,creator_id,format,invariant_pattern,confidence,source_evidence_id').eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle().then(({data})=>setLearning(data||null))},[])
 const person=CREATOR_OPTIONS.find(x=>x.id===creator)||CREATOR_OPTIONS[0]
 const packageData=result?.production_package||result
 const concepts=useMemo(()=>packageData?.concepts||packageData?.content_ideas||packageData?.ideas||[],[packageData])
 async function run(){setError('');setResult(null);if(url.trim())url.trim();else if(!direction.trim())return setError('Give Cornerstone a direction, trend, product or idea to work from.');setBusy(true);setMessage('Preparing creator intelligence…');try{
   let sourceEvidence=null
   if(url.trim()){
     const sourceUrl=normaliseSource(url.trim())
     setMessage('Acquiring reference content…')
     const{data:u,error:ue}=await supabase.auth.getUser();if(ue||!u?.user)throw new Error('Please sign in again.')
     const{data:queued,error:qe}=await supabase.from('local_ai_jobs').insert({owner_id:u.user.id,title:`Creator source · ${person.name} · ${platform}`,job_type:'creator_source_ingestion',model:'mlx-community/Qwen3-8B-4bit',persona_id:creator,system_prompt:'Acquire one public creator reference for local evidence inspection. Never claim inspection before media has been downloaded and analysed.',user_prompt:`Acquire and inspect this public creator reference: ${sourceUrl}`,options:{source_url:sourceUrl,original_url:sourceUrl,research_domain:'TRACK_B_CREATOR_GROWTH',workspace_id:'track_b',creator_platform:platform},status:'queued',production_status:'creator_source_queued'}).select('id').single());if(qe||!queued?.id)throw qe||new Error('Could not queue the creator reference.')
     const acquired=await job(queued.id,setMessage,'Reference acquisition');const acquiredData=parseJson(acquired.result||'{}');if(!acquiredData.media_job_id)throw new Error('Reference downloaded without creating its inspection job.');const media=await job(acquiredData.media_job_id,setMessage,'Reference inspection');const mediaData=parseJson(media.result||'{}');if(!mediaData.text_analysis_job_id)throw new Error('Reference inspection completed without creator analysis.');const analysis=await job(mediaData.text_analysis_job_id,setMessage,'Reference intelligence');sourceEvidence={acquisition:acquiredData,inspection:mediaData,analysis:parseJson(analysis.result||'{}')}
   }
   setMessage('Building the next creator move…')
   const{data:u,error:ue}=await supabase.auth.getUser();if(ue||!u?.user)throw new Error('Please sign in again.')
   const learningText=learning?`\nLATEST MEASURED LEARNING SIGNAL (direction only):\n${JSON.stringify(learning)}\nUse it to shape the next experiment, not to copy prior work.`:''
   const prompt=`CREATOR: ${person.name}\nCREATOR TONE: ${person.tone}\nPLATFORM: ${platform}\nOBJECTIVE: ${objective}\nFORMAT: ${format}\nDIRECTION: ${direction||'Choose the strongest evidence-backed opportunity.'}${learningText}\n${url.trim()?`\nINSPECTED REFERENCE EVIDENCE:\n${JSON.stringify(sourceEvidence)}`:''}\n\nBuild a creator-native package. Protect the selected creator identity and any character/relationship bible. Return a useful plan for content creation and monetisation. Include: operator brief, why this fits the creator, 8 ranked concepts, 5 hooks, 3 production directions, captions or talking points, CTA options, a 7-day test plan, metrics to watch, and monetisation tests relevant to ${objective}. For TikTok Shop, focus on product-content angles and measurable tests. For affiliate offers, focus on audience-fit offers and tracked conversion. For Fanvue/subscriber content, keep the strategy appropriate to the creator asset and focused on audience value, retention and conversion. Never promise earnings or invent performance metrics. Keep recommendations distinct from evidence.`
   const{data:created,error:ce}=await supabase.from('local_ai_jobs').insert({owner_id:u.user.id,title:`Creator strategy · ${person.name} · ${objective}`,job_type:'growth_mode',model:'mlx-community/Qwen3-8B-4bit',persona_id:creator,system_prompt:'You are Cornerstone creator strategy director. Protect creator identity. Build specific, platform-native, evidence-grounded creator growth and monetisation plans. Never invent analytics or promise income. JSON only.',user_prompt:prompt,options:{research:true,max_tokens:6500,temperature:.45,research_domain:'TRACK_B_CREATOR_GROWTH',workspace_id:'track_b',creator_platform:platform,creator_objective:objective,source_analysis:sourceEvidence},status:'queued',production_status:'creator_strategy_queued'}).select('id').single());if(ce||!created?.id)throw ce||new Error('Could not queue the creator strategy.');const finished=await job(created.id,setMessage,'Creator strategy');setResult(parseJson(finished.result||'{}'));setMessage('Creator package ready.')
 }catch(e){setError(e?.message||String(e));setMessage('')}finally{setBusy(false)}}
 return <main className="creator-studio"><section className="creator-hero"><div className="creator-kicker">CREATOR STUDIO</div><h1>Build the business around the girls, not just the platform.</h1><p>One engine for Cara, Lila and Cara + Lila across TikTok, Instagram, YouTube, Fanvue, affiliates and TikTok Shop. Content is the asset. Monetisation is the test.</p></section>
 <section className="creator-grid"><div className="creator-card"><div className="creator-label">Who is this for?</div><div className="creator-roster">{CREATOR_OPTIONS.map(p=><button key={p.id} className={creator===p.id?'active':''} onClick={()=>setCreator(p.id)}><strong>{p.name}</strong><span>{p.tone}</span></button>)}</div><div className="creator-form-grid"><label><span>Platform</span><select value={platform} onChange={e=>setPlatform(e.target.value)}>{PLATFORMS.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Objective</span><select value={objective} onChange={e=>setObjective(e.target.value)}>{OBJECTIVES.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Format</span><select value={format} onChange={e=>setFormat(e.target.value)}>{FORMATS.map(x=><option key={x}>{x}</option>)}</select></label></div><label className="creator-wide"><span>Reference content (optional)</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="YouTube, TikTok or Instagram URL"/></label><label className="creator-wide"><span>What are we trying?</span><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="Product, trend, affiliate offer, Fanvue angle, content idea, story, audience problem…"/></label>{learning?<div className="creator-learning"><strong>Latest learning is available.</strong><span>{learning.invariant_pattern||learning.format||'Measured creator learning will influence the next test.'}</span></div>:null}{error?<div className="creator-error">{error}</div>:null}<div className="creator-actions"><span>{message||'Reference → evidence → creator-native package → test → measure'}</span><button onClick={run} disabled={busy}>{busy?'Working…':'Build creator move →'}</button></div></div><aside className="creator-card creator-side"><div className="creator-label">Selected asset</div><h2>{person.name}</h2><p>{person.tone}. The strategy will stay inside this creator's identity rather than defaulting to generic YouTube advice.</p><div className="creator-lanes">{OBJECTIVES.map(x=><div key={x}>{x}</div>)}</div></aside></section>
 {result?<section className="creator-result"><div className="creator-label">PACKAGE READY</div><h2>{packageData?.recommended_subject||packageData?.angle||`Next move for ${person.name}`}</h2><div className="creator-result-grid"><article><span>Why it fits</span><p>{result?.operator_brief?.why||packageData?.why_this_should_work||packageData?.why_it_should_work||`Built for ${person.name}, ${platform}, and ${objective}.`}</p></article><article><span>Next action</span><p>{result?.operator_brief?.next_action||'Run the strongest ranked concept as a controlled test.'}</p></article></div>{concepts.length?<div className="creator-list">{concepts.slice(0,8).map((x,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{typeof x==='string'?x:x?.title||x?.concept||JSON.stringify(x)}</span></div>)}</div>:null}</section>:null}
 </main>
}
