import React from 'react';

const destinations = [
  { title: 'Track A', href: 'https://cornerstonegroupdatabase-bfc2v3f4m-100492107s-projects.vercel.app/', external: true, icon: '↗', accent: '#6f8cff' },
  { title: 'Track B', href: '/creative', external: false, icon: '✦', accent: '#d4af37' },
  { title: 'New Life', href: 'https://new-life-game-alpha.vercel.app/start-v2.html', external: true, icon: '◒', accent: '#bb8cff' },
];
function Card({ item }) { return <a href={item.href} target={item.external ? '_blank' : undefined} rel={item.external ? 'noreferrer' : undefined} style={{ display:'flex', minHeight:270, padding:28, borderRadius:28, color:'#f4f5f7', textDecoration:'none', background:'linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018))', border:'1px solid rgba(255,255,255,.08)', boxShadow:'0 20px 60px rgba(0,0,0,.22)', position:'relative', overflow:'hidden', transition:'transform .18s ease,border-color .18s ease,box-shadow .18s ease' }} onMouseEnter={e=>{e.currentTarget.style.transform='translateY(-5px)';e.currentTarget.style.borderColor=item.accent+'66';e.currentTarget.style.boxShadow='0 28px 80px rgba(0,0,0,.32)'}} onMouseLeave={e=>{e.currentTarget.style.transform='translateY(0)';e.currentTarget.style.borderColor='rgba(255,255,255,.08)';e.currentTarget.style.boxShadow='0 20px 60px rgba(0,0,0,.22)'}}><div style={{position:'absolute',right:'-12%',bottom:'-42%',width:260,height:260,borderRadius:'50%',background:item.accent,opacity:.10,filter:'blur(20px)'}}/><div style={{display:'flex',flexDirection:'column',width:'100%',justifyContent:'space-between',position:'relative',zIndex:1}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start'}}><div style={{width:54,height:54,borderRadius:17,display:'grid',placeItems:'center',background:item.accent+'18',border:'1px solid '+item.accent+'44',color:item.accent,fontSize:24,fontWeight:900}}>{item.icon}</div><div style={{width:34,height:34,borderRadius:12,display:'grid',placeItems:'center',background:'rgba(255,255,255,.04)',color:'#7d8695',fontSize:16}}>{item.external?'↗':'→'}</div></div><div><h2 style={{margin:0,fontSize:34,letterSpacing:'-.045em',fontWeight:850}}>{item.title}</h2><div style={{marginTop:14,fontSize:12,color:'#6f7888'}}>{item.external?'Open':'Enter'}</div></div></div></a> }
export default function EnterpriseHome(){return <div style={{minHeight:'100vh',background:'#07090d',color:'#f4f5f7',padding:'56px 34px 72px'}}><div style={{maxWidth:1280,margin:'0 auto'}}><header style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:56}}><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{width:44,height:44,borderRadius:14,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#e8c45b,#a97c25)',color:'#161109',fontSize:20,fontWeight:950}}>C</div><div style={{fontSize:18,fontWeight:850,letterSpacing:'-.025em'}}>Cornerstone AI Enterprise</div></div><div style={{width:8,height:8,borderRadius:50,background:'#72cda7',boxShadow:'0 0 18px rgba(114,205,167,.5)'}}/></header><main><h1 style={{margin:'0 0 34px',fontSize:'clamp(42px,6vw,72px)',lineHeight:.95,letterSpacing:'-.06em',fontWeight:850,maxWidth:760}}>Cornerstone AI Enterprise</h1><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:18}}>{destinations.map(item=><Card key={item.title} item={item}/>)}</div></main></div></div>}
