import React, { useEffect, useMemo, useState } from "react";
import EnterpriseShell from "./EnterpriseShell.jsx";
import { supabase } from "./supabase";

const SOURCES=[["pinterest","Pinterest","Pins, pose boards, outfit references"],["vinted","Vinted","Real clothing listings and silhouettes"],["depop","Depop","Vintage, street and editorial looks"]];
const CATS=["all","wardrobe","pose","scene","accessory","mixed"];
const PURPOSES=["wardrobe","pose","scene","shoot","mixed"];
const CREATOR_OPTIONS=[["cara","Cara"],["lila","Lila"],["duo","Cara + Lila"],["neutral","Neutral"]];

function sourceGuess(url){const v=String(url||"").toLowerCase();if(/pinterest\.|pin\.it/.test(v))return"pinterest";if(/vinted\./.test(v))return"vinted";if(/depop\.com/.test(v))return"depop";return"other";}
function badge(source){return source==="pinterest"?"PIN":source==="vinted"?"VINTED":source==="depop"?"DEPOP":"WEB";}

export default function ReferenceBoardWorkspace(){
 const [boards,setBoards]=useState([]),[boardId,setBoardId]=useState(""),[items,setItems]=useState([]);
 const [url,setUrl]=useState(""),[imageUrl,setImageUrl]=useState(""),[creator,setCreator]=useState("cara"),[purpose,setPurpose]=useState("mixed"),[category,setCategory]=useState("mixed"),[boardName,setBoardName]=useState("Cara · Visual Reference Board"),[filter,setFilter]=useState("all");
 const [busy,setBusy]=useState(false),[analysing,setAnalysing]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");

 async function currentUser(){const {data,error:e}=await supabase.auth.getUser();if(e||!data.user)throw new Error("Sign in required.");return data.user;}
 async function loadItems(id,f){if(!id){setItems([]);return;}const u=await currentUser();let q=supabase.from("cornerstone_visual_references").select("*").eq("owner_id",u.id).eq("board_id",id).order("created_at",{ascending:false});if(f&&f!=="all")q=q.eq("category",f);const {data,error:e}=await q;if(e)throw e;setItems(data||[]);}
 async function loadBoards(preferred){const u=await currentUser();const {data,error:e}=await supabase.from("cornerstone_visual_reference_boards").select("*").eq("owner_id",u.id).order("updated_at",{ascending:false});if(e)throw e;const next=data||[];setBoards(next);const chosen=preferred&&next.some(x=>x.id===preferred)?preferred:(next[0]&&next[0].id)||"";setBoardId(chosen);await loadItems(chosen,filter);}
 useEffect(()=>{loadBoards("").catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(boardId)loadItems(boardId,filter).catch(e=>setError(e.message));},[boardId,filter]);

 async function createBoard(){setBusy(true);setError("");setMessage("");try{const u=await currentUser();const {data,error:e}=await supabase.from("cornerstone_visual_reference_boards").insert({owner_id:u.id,name:boardName.trim()||"Visual Reference Board",creator_id:creator,purpose,description:"Reusable wardrobe, pose and scene references for owned creator production."}).select("*").single();if(e)throw e;setBoards(p=>[data,...p]);setBoardId(data.id);setItems([]);setMessage("Board created.");}catch(e){setError(e.message||String(e));}finally{setBusy(false);}}
 async function ingest(){setBusy(true);setError("");setMessage("");try{if(!boardId)throw new Error("Create or select a board first.");if(!url.trim())throw new Error("Paste a Pinterest, Vinted, Depop or public reference URL.");const {data:session}=await supabase.auth.getSession();const token=session&&session.session&&session.session.access_token;const response=await fetch("/api/reference-ingest",{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})},body:JSON.stringify({url:url.trim(),image_url:imageUrl.trim()||null})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Could not read source.");const u=await currentUser();const selectedCategory=category==="mixed"?(result.recipe&&result.recipe.category)||"mixed":category;const {data,error:e}=await supabase.from("cornerstone_visual_references").insert({owner_id:u.id,board_id:boardId,source_platform:result.source_platform||sourceGuess(url),source_url:result.source_url,canonical_url:result.canonical_url,image_url:result.image_url,title:result.title,description:result.description,media_type:"image",category:selectedCategory,tags:[result.source_platform||sourceGuess(url),selectedCategory],structured_data:result.structured_data||{},recipe:result.recipe||{},analysis:{},analysis_status:result.image_url?"pending":"no_image"}).select("*").single();if(e)throw e;setItems(p=>[data,...p]);setUrl("");setImageUrl("");setMessage(result.image_url?"Reference added. Auto analysis can now extract pose, wardrobe and scene structure.":"Reference saved without a preview image. Add an image URL when available.");}catch(e){setError(e.message||String(e));}finally{setBusy(false);}}
 async function analysePending(){setAnalysing(true);setError("");setMessage("");try{const u=await currentUser();const {data:pending,error:e}=await supabase.from("cornerstone_visual_references").select("id,image_url,title").eq("owner_id",u.id).eq("board_id",boardId).eq("analysis_status","pending").limit(24);if(e)throw e;const rows=pending||[];if(!rows.length){setMessage("Nothing is waiting for analysis.");return;}for(const item of rows){await supabase.from("cornerstone_visual_references").update({analysis_status:"processing",analysis_error:null}).eq("id",item.id).eq("owner_id",u.id);const {error:qError}=await supabase.from("local_ai_jobs").insert({owner_id:u.id,title:"Visual reference · "+(item.title||item.id),job_type:"visual_reference_analysis",model:"mlx-community/Qwen2.5-VL-3B-Instruct-4bit",persona_id:creator,system_prompt:"Analyse one public visual reference as original creative research. Do not identify the person. Extract reusable visual structure only. Return strict JSON.",user_prompt:"Analyse this image for Cornerstone wardrobe, pose, environment and composition. Image: "+item.image_url+" Structure only; never copy the person's face, branding or distinctive execution.",options:{reference_id:item.id,image_url:item.image_url,creator_id:creator},status:"queued",production_status:"reference_analysis_queued"});if(qError)await supabase.from("cornerstone_visual_references").update({analysis_status:"error",analysis_error:qError.message}).eq("id",item.id).eq("owner_id",u.id);}setMessage(rows.length+" reference(s) queued for local Qwen Vision analysis.");await loadItems(boardId,filter);}catch(e){setError(e.message||String(e));}finally{setAnalysing(false);}}
 async function remove(item){if(!window.confirm("Remove this reference from the board?"))return;const u=await currentUser();const {error:e}=await supabase.from("cornerstone_visual_references").delete().eq("id",item.id).eq("owner_id",u.id);if(e)setError(e.message);else setItems(p=>p.filter(x=>x.id!==item.id));}
 function applyBoard(){const selected=items.filter(x=>filter==="all"||x.category===filter).filter(x=>x.image_url);if(!selected.length){setError("Add at least one reference image before applying the board.");return;}const board=boards.find(x=>x.id===boardId);const pack={board_id:boardId,name:(board&&board.name)||"Visual Reference Board",creator:(board&&board.creator_id)||creator,purpose:(board&&board.purpose)||purpose,images:selected.slice(0,8).map(x=>x.image_url),references:selected.slice(0,8).map(x=>({id:x.id,source:x.source_platform,title:x.title,category:x.category,recipe:x.recipe||{},analysis:x.analysis||{},tags:x.tags||[]})),applied_at:new Date().toISOString()};sessionStorage.setItem("cornerstone_visual_reference_pack",JSON.stringify(pack));window.location.assign("/content/creators");}
 const openSource=source=>{const urls={pinterest:"https://www.pinterest.com/search/pins/?q=outfit%20pose%20reference",vinted:"https://www.vinted.co.uk/catalog?search_text=women%20outfit",depop:"https://www.depop.com/search/?q=women%20outfit"};window.open(urls[source],"_blank","noopener,noreferrer");};
 const visibleItems=useMemo(()=>items.filter(x=>filter==="all"||x.category===filter),[items,filter]);

 return <EnterpriseShell active="references" eyebrow="References"><main className="bi">
  <header className="bi-head"><div><div className="bi-k">Creator loop / Visual references</div><h1>Dress the idea before you generate it.</h1><p>Save public Pinterest, Vinted and Depop references, classify them, analyse them locally and reuse the resulting visual structure without changing creator identity.</p></div><div className="bi-head-meta"><b>{visibleItems.length} references</b><span>Board: {boards.find(x=>x.id===boardId)?.name||"none"}</span><small>Public page metadata + local Qwen Vision analysis</small></div></header>
  {error&&<div className="bi-error">{error}</div>}{message&&<div className="bi-success">{message}</div>}
  <section className="bi-grid2">
   <article className="bi-panel"><div className="bi-panel-head"><b>Board</b><span>Persistent visual input</span></div><div style={{padding:16,display:"grid",gap:11}}>
    <label className="bi-k">Select board<select value={boardId} onChange={e=>setBoardId(e.target.value)} style={{display:"block",width:"100%",marginTop:7}}><option value="">Create a new board…</option>{boards.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
    {!boardId&&<><label className="bi-k">Name<input value={boardName} onChange={e=>setBoardName(e.target.value)} style={{display:"block",width:"100%",marginTop:7}}/></label><label className="bi-k">Creator<select value={creator} onChange={e=>setCreator(e.target.value)} style={{display:"block",width:"100%",marginTop:7}}>{CREATOR_OPTIONS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="bi-k">Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)} style={{display:"block",width:"100%",marginTop:7}}>{PURPOSES.map(x=><option key={x} value={x}>{x}</option>)}</select></label><button className="bi-primary" disabled={busy} onClick={createBoard}>{busy?"Creating…":"Create board"}</button></>}
    {boardId&&<div className="bi-rule">Boards separate creator identity from visual structure. A board can become a reusable reference pack for generation.</div>}
   </div></article>
   <article className="bi-panel"><div className="bi-panel-head"><b>Add reference</b><span>Public source → recipe → local analysis</span></div><div style={{padding:16,display:"grid",gap:10}}>
    <div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{SOURCES.map(s=><button key={s[0]} className="bi-tab" onClick={()=>openSource(s[0])}>{s[1]} ↗</button>)}</div>
    <label className="bi-k">Public URL<input value={url} onChange={e=>setUrl(e.target.value)} style={{display:"block",width:"100%",marginTop:7}} placeholder="Pinterest Pin, Vinted listing or Depop item URL"/></label>
    <label className="bi-k">Optional image URL<input value={imageUrl} onChange={e=>setImageUrl(e.target.value)} style={{display:"block",width:"100%",marginTop:7}} placeholder="Use when the source hides its preview image"/></label>
    <label className="bi-k">Category<select value={category} onChange={e=>setCategory(e.target.value)} style={{display:"block",width:"100%",marginTop:7}}>{CATS.slice(1).map(x=><option key={x} value={x}>{x}</option>)}</select></label>
    <button className="bi-primary" disabled={busy||!boardId} onClick={ingest}>{busy?"Reading…":"Add reference"}</button>
    <div className="bi-rule">Use references as structure: silhouette, garment geometry, pose family, composition and environment. Creator identity remains anchored to Cornerstone's canonical refs.</div>
   </div></article>
  </section>
  <section className="bi-panel"><div className="bi-panel-head"><b>Reference library</b><span>{items.length} saved</span></div>
   <div style={{padding:"12px 16px",display:"flex",gap:7,flexWrap:"wrap"}}>{CATS.map(v=><button key={v} className={filter===v?"bi-tab active":"bi-tab"} onClick={()=>setFilter(v)}>{v}</button>)}<span style={{flex:1}}/><button className="bi-tab" onClick={analysePending} disabled={analysing}>{analysing?"Queueing…":"Auto analyse pending"}</button><button className="bi-primary" onClick={applyBoard}>Apply board to Creator</button></div>
   {visibleItems.length===0?<div className="bi-empty">No references in this view.</div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:12,padding:16}}>{visibleItems.map(item=><article key={item.id} style={{border:"1px solid var(--border)",borderRadius:16,overflow:"hidden",background:"var(--surface)"}}>
    <div style={{aspectRatio:"4/5",background:"var(--panel-2)",overflow:"hidden"}}>{item.image_url?<img src={item.image_url} alt="" style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/>:<div style={{display:"grid",placeItems:"center",height:"100%",padding:20,textAlign:"center"}}>No preview image</div>}</div>
    <div style={{padding:12}}><div className="bi-k">{badge(item.source_platform)} · {item.category}</div><strong style={{display:"block",marginTop:6}}>{item.title||"Untitled reference"}</strong><small style={{display:"block",marginTop:6,color:"var(--text-muted)"}}>{item.analysis_status==="complete"?"Analysed locally":item.analysis_status==="processing"?"Analysing…":item.analysis_status==="error"?"Analysis error":item.analysis_status==="no_image"?"Metadata only":"Waiting for analysis"}</small>{(item.analysis&&item.analysis.pose&&item.analysis.pose.family)||(item.analysis&&item.analysis.wardrobe&&item.analysis.wardrobe.silhouette)?<p style={{fontSize:11,lineHeight:1.5,color:"var(--text-muted)"}}>{(item.analysis&&item.analysis.pose&&item.analysis.pose.family)||(item.recipe&&item.recipe.category)||""} · {(item.analysis&&item.analysis.wardrobe&&(item.analysis.wardrobe.silhouette||item.analysis.wardrobe.fit))||""}</p>:null}<div style={{display:"flex",gap:7,marginTop:10}}><a href={item.source_url} target="_blank" rel="noreferrer" className="bi-tab">Open source ↗</a><button className="bi-tab" onClick={()=>remove(item)}>Remove</button></div></div>
   </article>)}</div>}
  </section>
 </main></EnterpriseShell>;
}
