import React, { useEffect, useState } from 'react';
import { supabase } from './supabase';

const PERSONAS=[
  {id:'cara',name:'Cara',note:'Direct, dry, disciplined, British'},
  {id:'lila',name:'Lila',note:'Warm, observant, understated'},
  {id:'cara_lila',name:'Cara + Lila',note:'Contrast, chemistry, two distinct voices'},
];
const FORMATS=['Personal moment','POV / relatable','Quick take','Micro-story','GRWM','Day in the life','Photo slideshow','Reaction'];

function Frame({eyebrow='Voices',title,copy,children}){return <main className="voice-workspace"><style>{`
 .voice-workspace{max-width:1160px;margin:0 auto;color:var(--text);font-family:var(--sans)}
 .vw-intro{padding:4px 0 26px}.vw-eyebrow{font-size:8px;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#a99773}.vw-title{margin:7px 0 0;font-family:var(--display);font-size:clamp(38px,5.2vw,62px);line-height:.93;letter-spacing:-.045em}.vw-copy{margin:10px 0 0;max-width:62ch;color:var(--text-muted);font-size:13px;line-height:1.6}
 .vw-card{margin-top:15px;padding:19px;border:1px solid var(--border);border-radius:18px;background:linear-gradient(180deg,rgba(255,255,255,.026),rgba(255,255,255,.01))}.vw-label{font-size:8px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:var(--text-subtle)}.vw-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:13px}.vw-choice{padding:15px;text-align:left;border:1px solid var(--border);border-radius:13px;background:#121419;color:var(--text);cursor:pointer;transition:.16s ease}.vw-choice:hover{transform:translateY(-1px);border-color:rgba(255,255,255,.15)}.vw-choice.active{border-color:rgba(216,195,154,.4);background:rgba(216,195,154,.075)}.vw-choice strong{display:block;font-family:var(--display);font-size:19px;font-weight:600;letter-spacing:-.02em}.vw-choice span{display:block;margin-top:5px;color:var(--text-muted);font-size:9px;line-height:1.45}
 .vw-field{display:grid;gap:6px;margin-top:14px}.vw-field label{font-size:8px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;color:var(--text-subtle)}.vw-field input,.vw-field select,.vw-field textarea{width:100%;min-height:44px;padding:11px 12px;border:1px solid var(--border);border-radius:10px;background:#0d0f13;color:var(--text);font:inherit;font-size:11px}.vw-field textarea{min-height:92px;resize:vertical;line-height:1.5}.vw-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.vw-btn{min-height:42px;padding:0 14px;border:1px solid var(--border);border-radius:10px;background:var(--surface-2);color:var(--text);font:inherit;font-size:10px;font-weight:850;cursor:pointer}.vw-btn.primary{background:#efe8da;color:#171614;border-color:#efe8da}.vw-btn:disabled{opacity:.5}.vw-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(216,195,154,.08);border:1px solid rgba(216,195,154,.18);color:#d8c8aa;font-size:8px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}.vw-list{display:grid;gap:7px;margin-top:14px}.vw-row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px 13px;border:1px solid var(--border);border-radius:11px;background:#121419}.vw-row strong{font-size:11px}.vw-row span{display:block;margin-top:4px;color:var(--text-muted);font-size:9px}.vw-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:14px}.vw-metric{padding:13px;border:1px solid var(--border);border-radius:12px;background:#121419}.vw-metric b{font-size:19px}.vw-metric span{display:block;margin-top:4px;font-size:8px;letter-spacing:.1em;text-transform:uppercase;color:var(--text-subtle)}.vw-message{margin-top:10px;color:var(--text-muted);font-size:10px;line-height:1.45}.vw-empty{padding:18px;border:1px dashed var(--border);border-radius:12px;color:var(--text-muted);font-size:10px;line-height:1.5}
 @media(max-width:720px){.vw-grid{grid-template-columns:1fr}.vw-metrics{grid-template-columns:1fr 1fr}.vw-actions{flex-direction:column}.vw-btn{width:100%}.vw-card{padding:16px}}
 `}</style><header className="vw-intro"><div className="vw-eyebrow">{eyebrow}</div><h1 className="vw-title">{title}</h1><p className="vw-copy">{copy}</p></header>{children}</main>}

export function CreatorsStaged({stage=0,onAdvance}){
 const [persona,setPersona]=useState('cara');const [format,setFormat]=useState(FORMATS[0]);const [direction,setDirection]=useState('');const [jobs,setJobs]=useState([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function load(){const {data,error}=await supabase.from('local_ai_jobs').select('id,title,status,created_at,persona_id,job_type').eq('job_type','growth_mode').order('created_at',{ascending:false}).limit(30);if(error)setMessage(error.message);setJobs(data||[])}
 useEffect(()=>{load()},[]);
 async function queue(){setBusy(true);setMessage('Building the brief…');const p=PERSONAS.find(x=>x.id===persona)||PERSONAS[0];const {error}=await supabase.from('local_ai_jobs').insert({title:`Creator package · ${p.name} · ${format}`,job_type:'growth_mode',model:'mlx-community/Qwen3-8B-4bit',persona_id:persona,system_prompt:'You are the creator strategy director for Cornerstone. Preserve creator identity and write specific, platform-native concepts. Return concise JSON.',user_prompt:`CREATOR: ${p.name}\nFORMAT: ${format}\nDIRECTION: ${direction||'Choose the strongest opportunity from the creator bible.'}\nReturn a package with hook, concept, outline, shot_list, caption, cta and why_it_should_work.`,options:{max_tokens:5000,temperature:.62},status:'queued',production_status:'not_started'});if(error)setMessage(error.message);else{setMessage('Brief created. It is ready for the next step.');await load()}setBusy(false)}
 if(stage===0)return <Frame title="Give every voice a point of view." copy="Choose the person first, then decide how they should show up. Cornerstone keeps the character consistent and turns your direction into something usable."><section className="vw-card"><div className="vw-label">Whose voice is this?</div><div className="vw-grid">{PERSONAS.map(p=><button key={p.id} className={`vw-choice${persona===p.id?' active':''}`} onClick={()=>setPersona(p.id)}><strong>{p.name}</strong><span>{p.note}</span></button>)}</div><div className="vw-field"><label>Format</label><select value={format} onChange={e=>setFormat(e.target.value)}>{FORMATS.map(f=><option key={f}>{f}</option>)}</select></div><div className="vw-actions"><button className="vw-btn primary" onClick={()=>{setMessage('Voice and format chosen.');onAdvance?.()}}>Continue with {PERSONAS.find(p=>p.id===persona)?.name} →</button></div>{message&&<div className="vw-message">{message}</div>}</section></Frame>;
 if(stage===1)return <Frame title="Give the idea a direction." copy="Tell Cornerstone what this person should make next. A rough thought is enough. It will turn it into a specific, usable package."><section className="vw-card"><span className="vw-badge">{PERSONAS.find(p=>p.id===persona)?.name} · {format}</span><div className="vw-field"><label>What should this feel like?</label><textarea value={direction} onChange={e=>setDirection(e.target.value)} placeholder="A story, a reaction, a point of view, a feeling, a trend worth owning…"/></div><div className="vw-actions"><button className="vw-btn primary" disabled={busy} onClick={queue}>{busy?'Building…':'Create the brief →'}</button><button className="vw-btn" onClick={()=>onAdvance?.()}>Go to Make</button></div>{message&&<div className="vw-message">{message}</div>}</section></Frame>;
 return <Frame eyebrow="Voices · recent work" title="Your creator work." copy="See what Cornerstone has already prepared for each voice. Completed packages can move into Make."><section className="vw-card"><div className="vw-metrics"><div className="vw-metric"><b>{jobs.length}</b><span>Created</span></div><div className="vw-metric"><b>{jobs.filter(j=>j.status==='queued').length}</b><span>Building</span></div><div className="vw-metric"><b>{jobs.filter(j=>j.status==='processing').length}</b><span>Working</span></div><div className="vw-metric"><b>{jobs.filter(j=>j.status==='completed').length}</b><span>Ready</span></div></div><div className="vw-list">{jobs.length?jobs.map(j=><div className="vw-row" key={j.id}><div><strong>{j.title}</strong><span>{j.persona_id} · {j.status} · {new Date(j.created_at).toLocaleString('en-GB')}</span></div></div>):<div className="vw-empty">No creator work yet. Choose a voice and create the first brief.</div>}</div></section></Frame>;
}

export function ShopStaged(){return <Frame eyebrow="Commerce" title="Commercial creative follows the same path." copy="Compatibility surface retained for older links. Active work moves through Create, Make, Publish and Learn."><section className="vw-card"><div className="vw-empty">Use the main content workflow for active work.</div></section></Frame>}
export function MediaStaged(){return <Frame eyebrow="Assets" title="Assets belong to the finished piece." copy="Source evidence and derived media are handled downstream of the creative decision."><section className="vw-card"><div className="vw-empty">Open Make to continue an active piece.</div></section></Frame>}
export function CaptionStudioStaged(){return <Frame eyebrow="Captions" title="Captions come after the creative is made." copy="The finished asset remains the source of truth for final rendering."><section className="vw-card"><div className="vw-empty">Continue from Make when the asset is ready.</div></section></Frame>}
export function LocalAIStaged(){const [jobs,setJobs]=useState([]);useEffect(()=>{(async()=>{const {data}=await supabase.from('local_ai_jobs').select('id,title,status,created_at').order('created_at',{ascending:false}).limit(20);setJobs(data||[])})()},[]);return <Frame eyebrow="System" title="The machinery stays behind the scenes." copy="You should experience the outcome, not the infrastructure. This compatibility view is intentionally minimal."><section className="vw-card"><div className="vw-list">{jobs.map(j=><div className="vw-row" key={j.id}><div><strong>{j.title}</strong><span>{j.status} · {new Date(j.created_at).toLocaleString('en-GB')}</span></div></div>)}{!jobs.length&&<div className="vw-empty">No recent activity.</div>}</div></section></Frame>}
