// api/generate-image.js
// Generates an image via fal.ai FLUX API from an image_prompt object stored in content_queue.
// Returns a public image URL which gets saved to content_queue.image_url.
//
// Model: fal-ai/flux/dev — $0.025/megapixel (~$0.02 per 1024x1024 image)
// Docs: https://fal.ai/models/fal-ai/flux/dev/api

const FAL_API_URL = "https://fal.run/fal-ai/flux/dev";

/**
 * Build a single flat prompt string from the structured image_prompt object
 * stored in content_queue (generated by generate-batch.js).
 */
function buildPrompt(imagePrompt, personaDescriptors) {
  if (!imagePrompt || typeof imagePrompt === "string") return imagePrompt || "";

  const {
    identity_lock = "",
    shot_angle = "",
    environment = "",
    lighting = "",
    wardrobe = "",
    mood = "",
    style_ref = "",
    composition = "",
  } = imagePrompt;

  // Build ordered prompt: identity first (most weight), then scene details
  const parts = [
    identity_lock || personaDescriptors,
    shot_angle,
    environment,
    lighting,
    wardrobe,
    mood,
    composition,
    style_ref,
    // Quality boosters
    "photorealistic, 8k, sharp focus, professional photography",
  ].filter(Boolean);

  return parts.join(", ");
}

const NEGATIVE_PROMPT = [
  "nudity", "bare breasts", "topless", "nsfw", "explicit",
  "blurry", "low quality", "watermark", "text", "logo",
  "deformed hands", "extra fingers", "mutation", "ugly",
  "cartoon", "anime", "illustration", "painting",
].join(", ");

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const apiKey = process.env.FAL_API_KEY;
  if (!apiKey) return res.status(500).json({ error: "FAL_API_KEY not configured" });

  let body;
  try {
    const chunks = [];
    for await (const chunk of req) chunks.push(chunk);
    body = JSON.parse(Buffer.concat(chunks).toString());
  } catch {
    return res.status(400).json({ error: "Invalid JSON body" });
  }

  const { imagePrompt, personaDescriptors, seed } = body;
  if (!imagePrompt) return res.status(400).json({ error: "imagePrompt required" });

  const prompt = buildPrompt(imagePrompt, personaDescriptors);

  const falBody = {
    prompt,
    negative_prompt: NEGATIVE_PROMPT,
    image_size: "portrait_4_3",   // 768x1024 — good for Fanvue feed
    num_inference_steps: 28,
    guidance_scale: 3.5,
    num_images: 1,
    enable_safety_checker: true,  // catches explicit content before it reaches you
    seed: seed || undefined,      // pass seed to regenerate same composition
    output_format: "jpeg",
  };

  let falRes;
  try {
    falRes = await fetch(FAL_API_URL, {
      method: "POST",
      headers: {
        "Authorization": `Key ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(falBody),
    });
  } catch (e) {
    return res.status(502).json({ error: "Network error reaching fal.ai", detail: e.message });
  }

  let data;
  try {
    data = await falRes.json();
  } catch {
    return res.status(502).json({ error: "Invalid response from fal.ai", status: falRes.status });
  }

  if (!falRes.ok) {
    console.error("fal.ai error:", falRes.status, JSON.stringify(data));
    return res.status(falRes.status).json({ error: "fal.ai rejected request", detail: data });
  }

  // Check if safety checker blocked it
  if (data?.has_nsfw_concepts?.[0] === true) {
    return res.status(200).json({
      blocked: true,
      reason: "Safety checker flagged this image. Try regenerating.",
      prompt,
    });
  }

  const imageUrl = data?.images?.[0]?.url;
  if (!imageUrl) {
    return res.status(502).json({ error: "No image URL in fal.ai response", raw: data });
  }

  return res.status(200).json({
    success: true,
    imageUrl,
    seed: data?.seed,
    prompt,
  });
}
