// Shared serverless bridge for Revenue Recovery, Content Engine and persistent generation data.
const SUPABASE_URL = 'https://zvyioxhwdyocaanzcgqf.supabase.co';
const OUTREACH_MODEL = process.env.QWEN_MODEL || 'mlx-community/Qwen3-8B-4bit';
function clean(value) { return String(value ?? '').trim(); }
function normaliseBusiness(business = {}) {
  return { id: clean(business.id), name: clean(business.name || business.businessName || business.dealerName), decisionMaker: clean(business.decisionMaker || business.ownerName || business.contact), email: clean(business.email), website: clean(business.website), location: clean(business.location || business.city || business.postcode), vertical: clean(business.vertical || business.industry), offer: clean(business.offer || business.product || business.service), leadSource: clean(business.leadSource), knownSignal: clean(business.knownSignal || business.observation || business.notes), status: clean(business.status), emailStage: Number(business.emailStage || 0), previousEmails: business.previousEmails || {} };
}
function stripModelThinking(value) { return String(value ?? '').replace(/<think>[\s\S]*?<\/think>/gi, '').replace(/<analysis>[\s\S]*?<\/analysis>/gi, '').replace(/<reasoning>[\s\S]*?<\/reasoning>/gi, '').trim(); }
function sanitiseJob(job) { if (!job) return job; const next = { ...job }; if (typeof next.result === 'string') next.result = stripModelThinking(next.result); if (typeof next.error_message === 'string') next.error_message = stripModelThinking(next.error_message); return next; }
function buildOutreachPrompt(business) {
  return `You are the senior outbound strategist for Cornerstone AI Enterprise's Track A Revenue Recovery operation.\n\nWORKSPACE / RESEARCH DOMAIN — HARD LOCK:\nTRACK_A_REVENUE_RECOVERY only. The niche is a PROBLEM DOMAIN, not a customer vertical: revenue leakage created when enquiries, leads, conversations, appointments, quotes or opportunities go cold, stale, unworked or fail to move toward a decision. Target businesses can be any legitimate lead-driven business.\n\nBUSINESS DATA — USE ONLY WHAT IS PROVIDED. NEVER INVENT FACTS.\n${JSON.stringify(business, null, 2)}\n\nCORE COMMERCIAL TRUTH:\nCornerstone helps businesses identify and recover revenue opportunities already entering the business. AI is the recovery mechanism: finding leakage patterns, prioritising recoverable opportunities, generating context-specific follow-up and keeping humans in control of the actual commercial conversation.\n\nCOMMERCIAL PATH:\nTarget account -> Recovery conversation -> Leakage diagnosis -> Controlled test -> Measured recovered opportunities -> Repeat / recurring support.\n\nEMAIL KPI: Get a reply from the right decision-maker. Start with the prospect's world. Surface a plausible leakage point. Ask one simple diagnostic question. Do not use pricing, feature dumps, AI jargon, fake certainty or unsupported claims. Do not pretend an unverified leakage point was audited. Use common workflow language when the fact is not supplied. Follow-ups must add a new angle. Borrow only abstract outreach mechanisms and never copy wording or distinctive execution.\n\nRETURN JSON ONLY:\n{\"recommended_subject\":\"\",\"subject_options\":[\"\",\"\",\"\"],\"email\":\"\",\"why_this_should_get_a_reply\":\"\",\"pattern_interrupt\":\"\",\"recovery_opportunity\":\"\",\"discovery_questions\":[\"\",\"\",\"\"],\"cta\":\"\",\"followup_plan\":{\"day_2_angle\":\"\",\"day_3_angle\":\"\",\"day_4_angle\":\"\",\"day_5_angle\":\"\"},\"quality_gate\":{\"prospect_first\":\"PASS\",\"problem_fit\":\"PASS\",\"replyability\":\"PASS\",\"specificity\":\"PASS\",\"human_voice\":\"PASS\",\"no_unsupported_claims\":\"PASS\",\"research_domain\":\"TRACK_A_REVENUE_RECOVERY\"}}`;
}
function buildContentEnginePrompt(payload) {
  const niche = clean(payload.niche || 'Choose the strongest opportunity from current evidence');
  return `You are the senior strategist of Cornerstone AI Enterprise's Track B Content Intelligence & Production Engine. WORKSPACE: TRACK_B_CONTENT_ENGINE.\nMISSION: find proven demand, understand why it works, build an original stronger version, multiply it into short-form, publish, measure and monetise.\n\nTARGET NICHE: ${niche}\nCHANNEL: ${clean(payload.channel) || 'Not fixed yet'}\nREFERENCE URL: ${clean(payload.referenceUrl) || 'None'}\nREFERENCE NOTES / TRANSCRIPT: ${clean(payload.referenceNotes) || 'None'}\nTARGET DURATION: ${clean(payload.duration || '20')} minutes\nOUTPUT: ${clean(payload.output || 'Long-form + Shorts')}\nEXTRA DIRECTION: ${clean(payload.direction) || 'None'}\n\nREFERENCE CONTENT IS A TEACHER, NOT A TEMPLATE. Use it to understand audience demand, topic appeal, hook structure, pacing, packaging, narrative mechanisms and weaknesses. Never reproduce exact wording, script, narration, footage, music, creator identity, branding, distinctive thumbnail or near-identical execution. The final work must be materially original.\n\nRESEARCH-FIRST: Prefer repeated public evidence over isolated viral outliers. Separate public signals from owned analytics. If a source is inaccessible, say so.\n\nBUILD: create an original stronger angle and long-form package with opportunity board, 10 titles, 3 thumbnails, hook, full spoken script, chapters, visual timeline, SEO/upload package, 5 follow-up ideas and a clear originality plan.\n\nMULTIPLY: create multiple standalone short-form derivatives with source windows, hooks, titles/captions and platform notes.\n\nMONETISE: propose measurable tests only. Potential routes include YouTube advertising where eligible, affiliate offers, TikTok Shop where available, Fanvue for the appropriate owned creator asset, sponsorships, subscriptions, products and licensing. Never promise revenue.\n\nRETURN JSON ONLY in the shape requested by the Content Engine interface.`;
}
async function readJob(serviceKey, id) { const r = await fetch(`${SUPABASE_URL}/rest/v1/local_ai_jobs?id=eq.${encodeURIComponent(id)}&select=id,title,job_type,model,persona_id,status,result,error_message,system_prompt,user_prompt,options,production_status,created_at,completed_at,video_url,captioned_video_url`, { headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`} }); const text=await r.text(); if(!r.ok) throw new Error(`Supabase read failed: ${text}`); const rows=JSON.parse(text); return sanitiseJob(rows[0]||null); }
async function listGenerations(serviceKey,{limit=1000,offset=0}={}) { const safeLimit=Math.max(1,Math.min(Number(limit)||1000,1000)); const safeOffset=Math.max(0,Number(offset)||0); const select='id,title,job_type,model,persona_id,status,result,error_message,system_prompt,user_prompt,options,production_status,created_at,completed_at,video_url,captioned_video_url'; const r=await fetch(`${SUPABASE_URL}/rest/v1/local_ai_jobs?select=${encodeURIComponent(select)}&order=created_at.desc&limit=${safeLimit}&offset=${safeOffset}`,{headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,Prefer:'count=exact'}}); const text=await r.text(); if(!r.ok) throw new Error(`Supabase list failed: ${text}`); const rows=JSON.parse(text).map(sanitiseJob); const range=r.headers.get('content-range')||''; const m=range.match(/\/([0-9]+)$/); const total=m?Number(m[1]):null; const nextOffset=rows.length===safeLimit?safeOffset+rows.length:null; return {rows,total,offset:safeOffset,limit:safeLimit,nextOffset,hasMore:nextOffset!==null&&(total===null||nextOffset<total)}; }
async function deleteGeneration(serviceKey,id){const r=await fetch(`${SUPABASE_URL}/rest/v1/local_ai_jobs?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`}});const text=await r.text();if(!r.ok)throw new Error(`Supabase delete failed: ${text}`);}
async function createJob(serviceKey,row){const r=await fetch(`${SUPABASE_URL}/rest/v1/local_ai_jobs`,{method:'POST',headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(row)});const text=await r.text();if(!r.ok)throw new Error(`Qwen queue failed: ${text}`);return JSON.parse(text)[0];}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.status(204).end();const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!SERVICE_KEY)return res.status(500).json({error:'SUPABASE_SERVICE_ROLE_KEY not configured'});
if(req.method==='GET'){const action=String(req.query?.action||''),id=String(req.query?.id||'').trim();try{if(['outreach_status','job_status'].includes(action)){if(!id||!/^[0-9a-f-]{36}$/i.test(id))return res.status(400).json({error:'Valid job id required'});const job=await readJob(SERVICE_KEY,id);if(!job)return res.status(404).json({error:'Job not found'});return res.status(200).json(job);}if(action==='generations'){const page=await listGenerations(SERVICE_KEY,{limit:req.query?.limit??1000,offset:req.query?.offset??0});return res.status(200).json({jobs:page.rows,total:page.total,offset:page.offset,limit:page.limit,nextOffset:page.nextOffset,hasMore:page.hasMore});}return res.status(400).json({error:'Unsupported GET action'});}catch(error){console.error('queue-update GET error',error);return res.status(500).json({error:error?.message||String(error)});}}
if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});let body;try{const chunks=[];for await(const chunk of req)chunks.push(chunk);body=JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{return res.status(400).json({error:'Invalid JSON body'});}
if(body.action==='delete_generation'){const id=String(body.id||'').trim();if(!id||!/^[0-9a-f-]{36}$/i.test(id))return res.status(400).json({error:'Valid generation id required'});try{await deleteGeneration(SERVICE_KEY,id);return res.status(200).json({success:true});}catch(error){return res.status(500).json({error:error?.message||String(error)});}}
if(body.action==='queue_outreach'){const business=normaliseBusiness(body.business||body.dealer);if(!business.name)return res.status(400).json({error:'business.name required'});try{const created=await createJob(SERVICE_KEY,{title:`Track A Revenue Recovery · ${business.name} · Email ${business.emailStage+1}`,job_type:'trend_scan',model:OUTREACH_MODEL,persona_id:'cornerstone_track_a_revenue_recovery',system_prompt:'You are Cornerstone AI Enterprise\'s Revenue Recovery strategist. Prospect-first. Problem-led. Evidence-grounded. This is not a dealership-only workflow.',user_prompt:buildOutreachPrompt(business),options:{max_tokens:6500,temperature:.52,research:true,outreach:true,recovery_business_id:business.id,research_domain:'TRACK_A_REVENUE_RECOVERY',workspace_id:'track_a',research_firewall:true},status:'queued',production_status:'not_started'});return res.status(200).json({jobId:created.id,business});}catch(error){console.error('queue_outreach error',error);return res.status(500).json({error:error?.message||String(error)});}}
if(body.action==='queue_content_engine'){try{const payload={niche:body.niche,channel:body.channel,referenceUrl:body.referenceUrl,referenceNotes:body.referenceNotes,duration:body.duration,output:body.output,direction:body.direction};const created=await createJob(SERVICE_KEY,{title:`Track B Content Engine · ${clean(payload.niche)||'Opportunity Discovery'}`,job_type:'content_engine',model:OUTREACH_MODEL,persona_id:'cornerstone_content_engine',system_prompt:'You are Cornerstone AI Enterprise\'s Track B Content Intelligence & Production Engine. Research current demand, learn from reference material without copying it, then build original content.',user_prompt:buildContentEnginePrompt(payload),options:{max_tokens:16000,temperature:.55,research:true,content_engine:true,research_domain:'TRACK_B_CONTENT_ENGINE',workspace_id:'track_b',reference_url:clean(payload.referenceUrl),niche:clean(payload.niche)},status:'queued',production_status:'not_started'});return res.status(200).json({jobId:created.id});}catch(error){console.error('queue_content_engine error',error);return res.status(500).json({error:error?.message||String(error)});}}
const{id,update}=body;if(!id||!update||typeof update!=='object')return res.status(400).json({error:'id and update object required'});const patchRes=await fetch(`${SUPABASE_URL}/rest/v1/content_queue?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(update)});if(!patchRes.ok){const err=await patchRes.text();return res.status(patchRes.status).json({error:`Supabase update failed: ${err}`});}return res.status(200).json({success:true});}
